name: local_auth_darwin
description: iOS implementation of the local_auth plugin.
repository: https://github.com/flutter/packages/tree/main/packages/local_auth/local_auth_darwin
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+local_auth%22
version: 1.2.2
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.19.3"

flutter:
  plugin:
    implements: local_auth
    platforms:
      ios:
        pluginClass: FLALocalAuthPlugin
        dartPluginClass: LocalAuthDarwin
        sharedDarwinSource: true

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.18.1 <0.20.0"
  local_auth_platform_interface: 
    git: https://github.com/kumsumit/local_auth_platform_interface.git

dev_dependencies:
  build_runner: ^2.4.2
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  pigeon: 
    git: https://github.com/kumsumit/pigeon.git

topics:
  - authentication
  - biometrics
  - local-auth
